#file: noinspection ComposeUnknownKeys,YAMLSchemaValidation
name: eclipse-world-plugin
recipe: laravel
config:
  webroot: workbench/public
  php: '8.3'
  via: nginx
services:
  appserver:
    type: php:custom
    xdebug: "debug,develop,coverage"
    environment:
      TZ: "Europe/Ljubljana"
      APP_BASE_PATH: "/app/workbench"
      TESTBENCH_WORKING_PATH: "/app"
    overrides:
      image: slimdeluxe/php:8.3-v1.2
      platform: linux/amd64
    run:
      - composer install --no-interaction --prefer-dist
      - composer run setup --no-interaction
      - composer run build --no-interaction
  appserver_nginx:
    scanner:
      path: /admin/login
      retry: 5
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  format:
    service: appserver
    description: Fix code style issues
    cmd: "composer format"
  testbench:
    service: appserver
    description: Run testbench CLI
    cmd: "vendor/bin/testbench"
