name: Update Shards

on:
  # Run weekly on Monday
  schedule:
    - cron: '0 0 * * 1'
  # Make it possible to run the workflow manually
  workflow_dispatch:

jobs:
  update-shards:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Update shards.json
        run: ./vendor/bin/pest --parallel --update-shards

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "test: update shards.json"
